# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MilvusBackup < Formula
  desc ""
  homepage "https://github.com/zilliztech/milvus-backup"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zhuwenxing/milvus-backup/releases/download/v0.4.0/milvus-backup_Darwin_x86_64.tar.gz"
      sha256 "73145cefa1132bc7a31d8d17d4d0930abc2010ce3b39cf13e0dfe540a1641625"

      def install
        bin.install "milvus-backup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zhuwenxing/milvus-backup/releases/download/v0.4.0/milvus-backup_Darwin_arm64.tar.gz"
      sha256 "141afb3fdfa90ac3964bdadc2731d6ac53e29a2a3aac70b2748be95293518819"

      def install
        bin.install "milvus-backup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zhuwenxing/milvus-backup/releases/download/v0.4.0/milvus-backup_Linux_x86_64.tar.gz"
      sha256 "b263e44c692297880230a42b210c2cdfee923537c2255742f0dcc2af46189ea8"

      def install
        bin.install "milvus-backup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhuwenxing/milvus-backup/releases/download/v0.4.0/milvus-backup_Linux_arm64.tar.gz"
      sha256 "3031635c06c189715e637728d8a78f5956626805ade932d6eb7b28e0401398c7"

      def install
        bin.install "milvus-backup"
      end
    end
  end
end
